### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by marmot21** [octol/vim-cpp-enhanced-highlight#39]
I have installed the plugin using Vundle, however I am not seeing the correct syntax highlighting.

![image](https://cloud.githubusercontent.com/assets/5285023/21589732/c3589506-d12f-11e6-86cb-5f38552a0a0e.png)

I have tried disabling all other plugs, no change.

**Comment by dawikur** [comment]
You need to set `g:cpp_experimental_simple_template_highlight` or `g:cpp_experimental_template_highlight` before loading **after/syntax/cpp.vim** file.
That's Because bit is checking those variables on creating syntax (when syntax file is parsed), not when source code is highlighted.

Simply add 
```vimL
let g:cpp_experimental_template_highligh =1
```
to your **vimrc**.

**Comment by marmot21** [comment]
I added that line to my vimrc file, no effect, but I see you're right - if I do `let g:cpp_experimental_template_highligh =1` then `set syntax=cpp` it works.

Why would it not be working when it's in the vimrc file?

**Comment by dawikur** [comment]
I would say wrong order of assigning variable and loading plugin, but I am not sure. I don't know your **vimrc** so this is just a guess.

**Comment by octol** [comment]
Glad the issue has been resolved. Closing.
